// <auto-generated />
using System;
using Juice.EventBus.Transactional.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Juice.EventBus.Transactional.Migrations.Migrations
{
    [DbContext(typeof(OutboxContext))]
    [Migration("20260205075636_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Juice.EventBus.Delivery.OutboxDelivery", b =>
                {
                    b.Property<Guid>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<DateTimeOffset?>("NextAttemptOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PublisherKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("DeliveryId");

                    b.HasIndex("CreationTime")
                        .HasDatabaseName("IX_OutboxDeliveries_Pending")
                        .HasFilter("[State] = 0")
                        .HasAnnotation("SqlServer:Include", new[] { "EventId", "PublisherKey" });

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("CreationTime"), new[] { "EventId", "PublisherKey" });

                    b.HasIndex("EventId");

                    b.HasIndex("NextAttemptOn")
                        .HasDatabaseName("IX_OutboxDeliveries_Retry")
                        .HasFilter("[State] = 3 AND [NextAttemptOn] IS NOT NULL")
                        .HasAnnotation("SqlServer:Include", new[] { "EventId", "PublisherKey" });

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("NextAttemptOn"), new[] { "EventId", "PublisherKey" });

                    b.HasIndex("ProcessedOn")
                        .HasDatabaseName("IX_OutboxDeliveries_Recovery")
                        .HasFilter("[State] = 1")
                        .HasAnnotation("SqlServer:Include", new[] { "EventId", "PublisherKey" });

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("ProcessedOn"), new[] { "EventId", "PublisherKey" });

                    b.HasIndex("PublisherKey");

                    b.ToTable("OutboxDeliveries", "App");
                });

            modelBuilder.Entity("Juice.EventBus.Delivery.OutboxEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventTypeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("EventId");

                    b.HasIndex("TransactionId");

                    b.ToTable("OutboxEvents", "App");
                });

            modelBuilder.Entity("Juice.EventBus.Delivery.OutboxDelivery", b =>
                {
                    b.HasOne("Juice.EventBus.Delivery.OutboxEvent", "OutboxEvent")
                        .WithMany("Deliveries")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OutboxEvent");
                });

            modelBuilder.Entity("Juice.EventBus.Delivery.OutboxEvent", b =>
                {
                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
