namespace Juice.MediatR
{
    /// <summary>
    /// Identified request with a unique ID to track duplicate requests for the same operation.
    /// </summary>
    public interface IIdempotentRequest: IBaseRequest
    {
        /// <summary>
        /// The IdempotencyKey must be generated by the caller, not server.
        /// <para></para> The unique identifier for the request, used to ensure idempotency by allowing the system to recognize and ignore duplicate requests with the same key.
        /// </summary>
        string IdempotencyKey { get; }
    }
}
