<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(AppTestTargetFramework)</TargetFrameworks>
        <OutputType>Exe</OutputType>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(TestSdk)" />
        <PackageReference Include="xunit.v3" Version="$(XUnitV3Version)" />
        <PackageReference Include="xunit.runner.visualstudio" Version="$(XUnitRunnerVersion)">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector" Version="6.0.2">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="FluentAssertions" Version="6.12.1" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\test\Juice.MultiTenant.TestHelper\Juice.MultiTenant.TestHelper.csproj" />
        <ProjectReference Include="..\..\..\test\Juice.XUnit\Juice.XUnit.csproj" />
        <ProjectReference Include="..\..\src\Juice.AspNetCore\Juice.AspNetCore.csproj" />
        <ProjectReference Include="..\..\src\Juice.Extensions.Logging\Juice.Extensions.Logging.csproj" />
        <ProjectReference Include="..\..\src\Juice.Extensions.MultiTenant\Juice.Extensions.MultiTenant.csproj" />
        <ProjectReference Include="..\..\src\Juice.Measurement\Juice.Measurement.csproj" />
        <ProjectReference Include="..\..\src\Juice\Juice.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.Separated.Development.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="appsettings.Development.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="tenants\TenantB\appsettings.Development.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Update="tenants\TenantA\appsettings.Development.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Logging.Configuration" Version="$(MicrosoftExtensionsVersion)" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="$(MicrosoftExtensionsVersion)" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="$(MicrosoftExtensionsVersion)" />
    </ItemGroup>

</Project>
