// <auto-generated />
using System;
using Juice.EventBus.IntegrationEventLog.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Juice.EventBus.IntegrationEventLog.EF.PostgreSQL.Migrations
{
    [DbContext(typeof(IntegrationEventLogContext))]
    [Migration("20260106080344_Indexing")]
    partial class Indexing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Juice.EventBus.IntegrationEventLog.EF.IntegrationEventLogEntry", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventTypeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("ModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("TimesSent")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("EventId");

                    b.HasIndex("TimesSent")
                        .HasDatabaseName("IX_IntegrationEventLog_Poison")
                        .HasFilter("[TimesSent] > 0");

                    b.HasIndex("TransactionId");

                    b.HasIndex("State", "ModificationTime", "TimesSent")
                        .HasDatabaseName("IX_IntegrationEventLog_Recovery")
                        .HasFilter("[ModificationTime] IS NOT NULL");

                    b.ToTable("IntegrationEventLog", "EventBus");
                });
#pragma warning restore 612, 618
        }
    }
}
