<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(AppTargetFramework)</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Juice</RootNamespace>
        <GraphQLServer>5.2.2</GraphQLServer>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <OpenApiGenerateDocuments>false</OpenApiGenerateDocuments>
        <NoWarn>$(NoWarn);1591</NoWarn>
    </PropertyGroup>

    <ItemGroup Label="AspNetCore">
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup Label="Open API">
        <PackageReference Include="Microsoft.Bcl.Memory" Version="9.0.15" />
        <PackageReference Include="Newtonsoft.Json" Version="*" />
        <PackageReference Include="Microsoft.OpenApi" Version="1.6.22" />
        <PackageReference Include="Microsoft.Identity.Web" Version="3.8.*" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="$(SwashbuckleVersion)" />
        <PackageReference Include="Swashbuckle.AspNetCore.Newtonsoft" Version="$(SwashbuckleVersion)" />
    </ItemGroup>

    <ItemGroup Label="GraphQL">
        <PackageReference Include="GraphQL" Version="8.1.0" />
        <PackageReference Include="GraphQL.SystemTextJson" Version="8.1.0" />
        <PackageReference Include="GraphQL.Server.Core" Version="$(GraphQLServer)" />
        <PackageReference Include="GraphQL.Server.Transports.AspNetCore" Version="8.0.3" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="$(EFVersion)" />
        <PackageReference Include="Juice.Modular" Version="10.0.1" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Juice.Extensions.Options\Juice.Extensions.Options.csproj" />
        <ProjectReference Include="..\Juice.Messaging\Juice.Messaging.csproj" />
        <ProjectReference Include="..\Juice\Juice.csproj" />
    </ItemGroup>

</Project>
