<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(AppTargetFramework)</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Description>EF core migration assembly</Description>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Juice.Messaging.Idempotency.EF\Juice.Messaging.Idempotency.EF.csproj" />
    </ItemGroup>

</Project>
