// <auto-generated />
using System;
using Juice.EventBus.IntegrationEventLog.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Juice.EventBus.IntegrationEventLog.EF.SqlServer.Migrations
{
    [DbContext(typeof(IntegrationEventLogContext))]
    [Migration("20260106075305_Indexing")]
    partial class Indexing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Juice.EventBus.IntegrationEventLog.EF.IntegrationEventLogEntry", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("TimesSent")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EventId");

                    b.HasIndex("TimesSent")
                        .HasDatabaseName("IX_Outbox_Poison")
                        .HasFilter("[TimesSent] > 0");

                    b.HasIndex("TransactionId");

                    b.HasIndex("State", "ModificationTime", "TimesSent")
                        .HasDatabaseName("IX_Outbox_Recovery")
                        .HasFilter("[ModificationTime] IS NOT NULL");

                    b.ToTable("IntegrationEventLog", "EventBus");
                });
#pragma warning restore 612, 618
        }
    }
}
