<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(AppTestTargetFramework)</TargetFrameworks>
        <OutputType>Exe</OutputType>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>

        <UserSecretsId>65263338-6ac0-4c7e-a191-af36c9c7405a</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(TestSdk)" />
        <PackageReference Include="xunit.v3" Version="$(XUnitV3Version)" />
        <PackageReference Include="xunit.runner.visualstudio" Version="$(XUnitRunnerVersion)">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector" Version="6.0.2">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>

        <PackageReference Include="FluentAssertions" Version="6.12.1" />
    </ItemGroup>

    <ItemGroup Label="Migrations">
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="$(NpgsqlVersion)" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="$(EFVersion)" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="$(EFVersion)">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="$(EFVersion)">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Finbuckle.MultiTenant.AspNetCore" Version="$(FinbuckleVersion)" />
        <PackageReference Include="Microsoft.Extensions.Logging.Configuration" Version="$(MicrosoftExtensionsVersion)" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="$(MicrosoftExtensionsVersion)" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="$(MicrosoftExtensionsVersion)" />
        <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="$(MicrosoftExtensionsVersion)" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\test\Juice.MultiTenant.TestHelper\Juice.MultiTenant.TestHelper.csproj" />
        <ProjectReference Include="..\..\..\test\Juice.XUnit\Juice.XUnit.csproj" />
        <ProjectReference Include="..\..\src\Juice.AspNetCore\Juice.AspNetCore.csproj" />
        <ProjectReference Include="..\..\src\Juice.EF.MultiTenant\Juice.EF.MultiTenant.csproj" />
        <ProjectReference Include="..\..\src\Juice.EF\Juice.EF.csproj" />
        <ProjectReference Include="..\Juice.EF.Tests.PostgreSQL\Juice.EF.Tests.PostgreSQL.csproj" />
        <ProjectReference Include="..\Juice.EF.Tests.Shared\Juice.EF.Tests.Shared.csproj" />
        <ProjectReference Include="..\Juice.EF.Tests.SqlServer\Juice.EF.Tests.SqlServer.csproj" />
    </ItemGroup>


    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>


</Project>
