<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(AppTargetFramework)</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup Label="AspNetCore">
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
        <PackageReference Include="Finbuckle.MultiTenant.AspNetCore" Version="$(FinbuckleVersion)" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\core\src\Juice.Extensions.MultiTenant\Juice.Extensions.MultiTenant.csproj" />
        <ProjectReference Include="..\..\core\src\Juice\Juice.csproj" />
    </ItemGroup>
</Project>
