<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(AppTestTargetFramework)</TargetFrameworks>
        <OutputType>Exe</OutputType>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>

        <UserSecretsId>be895864-5a80-43bd-bf26-52f5823e0c0c</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(TestSdk)" />
        <PackageReference Include="xunit.v3" Version="$(XUnitV3Version)" />
        <PackageReference Include="xunit.runner.visualstudio" Version="$(XUnitRunnerVersion)">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector" Version="6.0.2">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Label="Integration tests" Include="Microsoft.AspNetCore.Mvc.Testing" Version="$(MvcTesting)" />
    </ItemGroup>


    <ItemGroup Label="Migrations">
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="$(EFVersion)">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="$(EFVersion)">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\test\Juice.Tests.Host\Juice.Tests.Host.csproj" />
        <ProjectReference Include="..\..\src\Juice.EventBus.RabbitMQ\Juice.EventBus.RabbitMQ.csproj" />
        <ProjectReference Include="..\..\src\Juice.Extensions.MultiTenant\Juice.Extensions.MultiTenant.csproj" />
        <ProjectReference Include="..\..\src\Juice.Messaging.Idempotency.EF\Juice.Messaging.Idempotency.EF.csproj" />
        <ProjectReference Include="..\..\src\Juice.Messaging.Idempotency.Redis\Juice.Messaging.Idempotency.Redis.csproj" />
        <ProjectReference Include="..\..\src\Juice.Messaging.Outbox.Delivery\Juice.Messaging.Outbox.Delivery.csproj" />
        <ProjectReference Include="..\..\src\Juice.Messaging.Outbox.EF\Juice.Messaging.Outbox.EF.csproj" />
        <ProjectReference Include="..\..\src\Juice.Messaging.Outbox.Migrations.PostgreSQL\Juice.Messaging.Outbox.Migrations.PostgreSQL.csproj" />
        <ProjectReference Include="..\..\src\Juice.Messaging.Outbox.Migrations.SqlServer\Juice.Messaging.Outbox.Migrations.SqlServer.csproj" />
        <ProjectReference Include="..\Juice.EF.Tests\Juice.EF.Tests.csproj" />
    </ItemGroup>

    <ItemGroup>
        <None Update="appsettings.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
