<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(AppTargetFramework)</TargetFrameworks>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>

    <UserSecretsId>de0004e0-598d-45c6-b5f7-52cffd6f1b08</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="$(TestSdk)" />
    <PackageReference Include="xunit" Version="$(XUnitVersion)" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="6.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Juice.MediatR.Behaviors\Juice.MediatR.Behaviors.csproj" />
    <ProjectReference Include="..\Juice.EF.Tests.PostgreSQL\Juice.EF.Tests.PostgreSQL.csproj" />
    <ProjectReference Include="..\Juice.EF.Tests.SqlServer\Juice.EF.Tests.SqlServer.csproj" />
    <ProjectReference Include="..\Juice.EF.Tests\Juice.EF.Tests.csproj" />
    <ProjectReference Include="..\Juice.EventBus.Tests\Juice.EventBus.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
