<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(AppTargetFramework)</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Description>EventBus abstractions</Description>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="$(MicrosoftExtensionsVersion)" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="$(MicrosoftExtensionsVersion)" />
        <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" Version="$(MicrosoftExtensionsVersion)" />
        <PackageReference Include="Microsoft.Extensions.Logging" Version="$(MicrosoftExtensionsVersion)" />
        <PackageReference Include="Microsoft.Extensions.Options" Version="$(MicrosoftExtensionsVersion)" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="$(MicrosoftExtensionsVersion)" />
        <PackageReference Include="Newtonsoft.Json" Version="*" />
        <PackageReference Include="Polly" Version="8.6.4" />
    </ItemGroup>

    <ItemGroup Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net9.0'))">
        <PackageReference Include="Backport.System.Threading.Lock" Version="3.1.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Juice.EventBus.Contracts\Juice.EventBus.Contracts.csproj" />
      <ProjectReference Include="..\Juice.Measurement\Juice.Measurement.csproj" />
      <ProjectReference Include="..\Juice.Messaging\Juice.Messaging.csproj" />
    </ItemGroup>

</Project>
