// <auto-generated />
using System;
using Juice.Messaging.Outbox.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Juice.Messaging.Outbox.Migrations.SqlServer
{
    [DbContext(typeof(OutboxContext))]
    [Migration("20260521000001_AddProcessedByToDelivery")]
    partial class AddProcessedByToDelivery
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Juice.Messaging.Outbox.OutboxDelivery", b =>
                {
                    b.Property<Guid>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTimeOffset?>("NextAttemptOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ProcessedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PublisherKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("RoutingKey")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("DeliveryId");

                    b.HasIndex("CreationTime")
                        .HasDatabaseName("IX_OutboxDeliveries_Pending")
                        .HasFilter("[State] = 0")
                        .HasAnnotation("Npgsql:IndexInclude", new[] { "EventId", "PublisherKey" });

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("CreationTime"), new[] { "EventId", "PublisherKey" });

                    b.HasIndex("EventId");

                    b.HasIndex("NextAttemptOn")
                        .HasDatabaseName("IX_OutboxDeliveries_Retry")
                        .HasFilter("[State] = 3 AND [NextAttemptOn] IS NOT NULL")
                        .HasAnnotation("Npgsql:IndexInclude", new[] { "EventId", "PublisherKey" });

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("NextAttemptOn"), new[] { "EventId", "PublisherKey" });

                    b.HasIndex("ProcessedOn")
                        .HasDatabaseName("IX_OutboxDeliveries_Recovery")
                        .HasFilter("[State] = 1")
                        .HasAnnotation("Npgsql:IndexInclude", new[] { "EventId", "PublisherKey" });

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ProcessedOn"), new[] { "EventId", "PublisherKey" });

                    b.HasIndex("PublisherKey");

                    b.ToTable("OutboxDeliveries", "App");
                });

            modelBuilder.Entity("Juice.Messaging.Outbox.OutboxEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EventTypeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Headers")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("{}");

                    b.Property<byte[]>("PayloadBytes")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("TenantId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("EventId");

                    b.HasIndex("TransactionId");

                    b.ToTable("OutboxEvents", "App");
                });

            modelBuilder.Entity("Juice.Messaging.Outbox.OutboxDelivery", b =>
                {
                    b.HasOne("Juice.Messaging.Outbox.OutboxEvent", "OutboxEvent")
                        .WithMany("Deliveries")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OutboxEvent");
                });

            modelBuilder.Entity("Juice.Messaging.Outbox.OutboxEvent", b =>
                {
                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
