global using Juice.EF;
global using Juice.Extensions.DependencyInjection;
global using Juice.Workflows.Domain.AggregatesModel.DefinitionAggregate;
global using Juice.Workflows.Domain.AggregatesModel.WorkflowAggregate;
global using Juice.Workflows.Domain.AggregatesModel.WorkflowStateAggregate;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Design;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
