<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>$(AppTargetFramework)</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Description>Define IdentifiedCommand abstraction and RequestManager for mediator's deduplicated command handler</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="DependencyInjection\MediatorServiceCollectionExtensions.cs~RF54975a25.TMP" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="$(MicrosoftExtensionsVersion)" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="$(MicrosoftExtensionsVersion)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Juice.Contracts\Juice.Contracts.csproj" />
    <ProjectReference Include="..\Juice.MediatR.Contracts\Juice.MediatR.Contracts.csproj" />
  </ItemGroup>
</Project>
