// <auto-generated />
using System;
using Juice.Audit.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Juice.Audit.EF.SqlServer.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20230914024519_InitAuditLog")]
    partial class InitAuditLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Juice.Audit.Domain.AccessLogAggregate.AccessLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("User")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DateTime");

                    b.HasIndex("User", "Action");

                    b.ToTable("AccessLog", (string)null);
                });

            modelBuilder.Entity("Juice.Audit.Domain.DataAuditAggregate.DataAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AccessId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("DataChanges")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Database")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Table")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("User")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AccessId");

                    b.HasIndex("DateTime");

                    b.HasIndex("User", "Action");

                    b.HasIndex("Database", "Schema", "Table");

                    b.ToTable("DataAudit", (string)null);
                });

            modelBuilder.Entity("Juice.Audit.Domain.AccessLogAggregate.AccessLog", b =>
                {
                    b.OwnsOne("Juice.Audit.Domain.AccessLogAggregate.RequestInfo", "RequestInfo", b1 =>
                        {
                            b1.Property<Guid>("AccessLogId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AccessZone")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Data")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Headers")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Host")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Method")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Path")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("QueryString")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("RemoteIpAddress")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("RequestId")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Schema")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AccessLogId");

                            b1.ToTable("AccessLog");

                            b1.WithOwner()
                                .HasForeignKey("AccessLogId");
                        });

                    b.OwnsOne("Juice.Audit.Domain.AccessLogAggregate.ResponseInfo", "ResponseInfo", b1 =>
                        {
                            b1.Property<Guid>("AccessLogId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Data")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Error")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Headers")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Message")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("StatusCode")
                                .HasColumnType("int");

                            b1.HasKey("AccessLogId");

                            b1.ToTable("AccessLog");

                            b1.WithOwner()
                                .HasForeignKey("AccessLogId");
                        });

                    b.OwnsOne("Juice.Audit.Domain.AccessLogAggregate.ServerInfo", "ServerInfo", b1 =>
                        {
                            b1.Property<Guid>("AccessLogId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("AppName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("MachineName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("OSVersion")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SoftwareVersion")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("AccessLogId");

                            b1.ToTable("AccessLog");

                            b1.WithOwner()
                                .HasForeignKey("AccessLogId");
                        });

                    b.Navigation("RequestInfo");

                    b.Navigation("ResponseInfo");

                    b.Navigation("ServerInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
