<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>$(AppTargetFramework)</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Juice.EventBus</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Juice.Contracts\Juice.Contracts.csproj" />
    </ItemGroup>

</Project>
