// <auto-generated />
using System;
using Juice.EventBus.Transactional.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Juice.EventBus.Transactional.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(OutboxContext))]
    partial class OutboxContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Juice.EventBus.Delivery.OutboxDelivery", b =>
                {
                    b.Property<Guid>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTimeOffset?>("NextAttemptOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcessedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PublisherKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("DeliveryId");

                    b.HasIndex("CreationTime")
                        .HasDatabaseName("IX_OutboxDeliveries_Pending")
                        .HasFilter("[State] = 0")
                        .HasAnnotation("Npgsql:IndexInclude", new[] { "EventId", "PublisherKey" });

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("CreationTime"), new[] { "EventId", "PublisherKey" });

                    b.HasIndex("EventId");

                    b.HasIndex("NextAttemptOn")
                        .HasDatabaseName("IX_OutboxDeliveries_Retry")
                        .HasFilter("[State] = 3 AND [NextAttemptOn] IS NOT NULL")
                        .HasAnnotation("Npgsql:IndexInclude", new[] { "EventId", "PublisherKey" });

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("NextAttemptOn"), new[] { "EventId", "PublisherKey" });

                    b.HasIndex("ProcessedOn")
                        .HasDatabaseName("IX_OutboxDeliveries_Recovery")
                        .HasFilter("[State] = 1")
                        .HasAnnotation("Npgsql:IndexInclude", new[] { "EventId", "PublisherKey" });

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("ProcessedOn"), new[] { "EventId", "PublisherKey" });

                    b.HasIndex("PublisherKey");

                    b.ToTable("OutboxDeliveries", "App");
                });

            modelBuilder.Entity("Juice.EventBus.Delivery.OutboxEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventTypeName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("EventId");

                    b.HasIndex("TransactionId");

                    b.ToTable("OutboxEvents", "App");
                });

            modelBuilder.Entity("Juice.EventBus.Delivery.OutboxDelivery", b =>
                {
                    b.HasOne("Juice.EventBus.Delivery.OutboxEvent", "OutboxEvent")
                        .WithMany("Deliveries")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OutboxEvent");
                });

            modelBuilder.Entity("Juice.EventBus.Delivery.OutboxEvent", b =>
                {
                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
