name: Pack alpha packages

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '*.md'

jobs:
  build:
    uses: creatorflow-io/shared-workflows/.github/workflows/shared-pack.yml@master
    with:
       Stage: alpha
       JuiceRefVersion: 6.0.0
    secrets: inherit