name: Nuget.org Release

on:
  release:
    types:
      - published


jobs:
    build:
      uses: creatorflow-io/shared-workflows/.github/workflows/shared-publish.yml@net8
      secrets: inherit
      with:
        Target: |
          6.0.x
          8.0.x
          9.0.x